apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-site4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: nu-exista-db
