apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wp-site1

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: wordpress
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: wordpress:6-php8.2-apache
  - target:
      kind: Ingress
      name: wordpress-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: site1.local
  - target:
      kind: Ingress
      name: phpmyadmin-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pma-site1.local
  - target:
      kind: Service
      name: wordpress
    patch: |
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081
  - target:
      kind: Service
      name: phpmyadmin
    patch: |
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31181
