apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb.yaml
  - redis.yaml
  - wordpress.yaml
  - phpmyadmin.yaml
  - resource-limits.yaml
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: wordpress
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value:
          kubernetes.io/ingress-bandwidth: 50M
          kubernetes.io/egress-bandwidth: 50M
  - target:
      kind: Deployment
      name: mariadb
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value:
          kubernetes.io/ingress-bandwidth: 20M
          kubernetes.io/egress-bandwidth: 20M
