apiVersion: v1
kind: Secret
metadata:
  name: wp-secrets
type: Opaque
stringData:
  # Valorile default - vor fi suprascrise per-site prin Vault
  # Vault path: secret/data/wordpress/<site-name>
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: CHANGE_ME
  WORDPRESS_DB_HOST: mariadb
  WORDPRESS_DB_USER: wpuser
  WORDPRESS_DB_PASSWORD: CHANGE_ME
  WORDPRESS_DB_NAME: wordpress
