apiVersion: v1
kind: Secret
metadata:
  name: gitea-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: http://gitea.gitea.svc:3000/argocd/k8s-apps.git
  # Credentialele vor fi gestionate prin Vault
  # Vault path: secret/data/argocd/gitea-repo
  username: CHANGE_ME
  password: CHANGE_ME
