apiVersion: v1
kind: Secret
metadata:
  name: gitea-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: http://gitea.gitea.svc:3000/argocd/k8s-apps.git
  username: argocd
  password: argocd123
