apiVersion: v1
kind: Secret
metadata:
  name: wp-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass123
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: wppass123
  WORDPRESS_DB_HOST: mariadb
  WORDPRESS_DB_USER: wpuser
  WORDPRESS_DB_PASSWORD: wppass123
  WORDPRESS_DB_NAME: wordpress
