apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-site3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-fantoma
            - name: WORDPRESS_DB_PASSWORD
              value: "parola123"
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
