apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wp-site2

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: wordpress-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: site2.local
  - target:
      kind: Ingress
      name: phpmyadmin-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pma-site2.local
  - target:
      kind: Service
      name: wordpress
    patch: |
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30082
  - target:
      kind: Service
      name: phpmyadmin
    patch: |
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31182
